REPLACE INTO "metadata" VALUES('DB_MAJOR',4,'');
REPLACE INTO "metadata" VALUES('DB_MINOR',1,'');
REPLACE INTO "metadata_real" VALUES('global_discount_rate',0.05,'');
REPLACE INTO "metadata_real" VALUES('default_loan_rate',0.05,'');
REPLACE INTO "time_period" VALUES(0,2015,'e');
REPLACE INTO "time_period" VALUES(1,2020,'f');
REPLACE INTO "time_period" VALUES(2,2025,'f');
REPLACE INTO "time_period" VALUES(3,2030,'f');
REPLACE INTO "time_period_type" VALUES('e','existing');
REPLACE INTO "time_period_type" VALUES('f','future');
REPLACE INTO "time_season" VALUES(0,'summer',0.5,NULL);
REPLACE INTO "time_season" VALUES(1,'winter',0.5,NULL);
REPLACE INTO "time_of_day" VALUES(0,'day',12,NULL);
REPLACE INTO "time_of_day" VALUES(1,'night',12,NULL);
REPLACE INTO "region" VALUES('A',NULL);
REPLACE INTO "region" VALUES('B',NULL);
REPLACE INTO "region" VALUES('C',NULL);
REPLACE INTO "commodity_type" VALUES('s','source');
REPLACE INTO "commodity_type" VALUES('a','annual');
REPLACE INTO "commodity_type" VALUES('p','physical');
REPLACE INTO "commodity_type" VALUES('d','demand');
REPLACE INTO "commodity_type" VALUES('e','emissions');
REPLACE INTO "commodity_type" VALUES('w','waste');
REPLACE INTO "commodity_type" VALUES('wa','waste annual');
REPLACE INTO "commodity_type" VALUES('wp','waste physical');
REPLACE INTO "commodity" VALUES('ethos','s',NULL,NULL);
REPLACE INTO "commodity" VALUES('NG','p',NULL,NULL);
REPLACE INTO "commodity" VALUES('ELC','p',NULL,NULL);
REPLACE INTO "commodity" VALUES('ELC_C','a',NULL,NULL);    -- annual electricity in C
REPLACE INTO "commodity" VALUES('HEAT','d',NULL,NULL);
REPLACE INTO "commodity" VALUES('HEAT_C','d',NULL,NULL);
REPLACE INTO "technology_type" VALUES('p','production');
REPLACE INTO "technology_type" VALUES('pb','baseload production');
REPLACE INTO "technology_type" VALUES('ps','storage production');
REPLACE INTO "technology" VALUES('NGCC','p',NULL,NULL,NULL,  0,0,0,0,0,0,0,  'combined-cycle gas');
REPLACE INTO "technology" VALUES('SOLPV','p',NULL,NULL,NULL, 0,0,1,0,0,0,0,  'solar photovoltaic');
REPLACE INTO "technology" VALUES('E_BATT','ps',NULL,NULL,NULL,0,0,0,0,0,0,0, 'grid battery');
REPLACE INTO "technology" VALUES('ANN_IMP','p',NULL,NULL,NULL,0,1,0,0,0,0,0, 'capacitated annual import');
REPLACE INTO "technology" VALUES('HEAT_SYS','p',NULL,NULL,NULL,0,0,0,0,0,0,0,'electric heater');
REPLACE INTO "technology" VALUES('HEAT_ANN','p',NULL,NULL,NULL,0,1,0,0,0,0,0,'annual electric heater');
REPLACE INTO "technology" VALUES('IMP_NG','p',NULL,NULL,NULL,  1,0,0,0,0,0,0,  'unlimited NG import');
REPLACE INTO "technology" VALUES('E_TRANS','p',NULL,NULL,NULL,0,0,0,0,0,1,0, 'interregional transmission');
REPLACE INTO "tech_group" VALUES('elec_A',     'generators + storage + load in A');
REPLACE INTO "tech_group" VALUES('elec_AB',    'generators + storage + exchange + load across A and B');
REPLACE INTO "tech_group" VALUES('elec_C_ann', 'annual import + load in C');
REPLACE INTO "tech_group_member" VALUES('elec_A',     'NGCC');
REPLACE INTO "tech_group_member" VALUES('elec_A',     'SOLPV');
REPLACE INTO "tech_group_member" VALUES('elec_A',     'E_BATT');
REPLACE INTO "tech_group_member" VALUES('elec_A',     'HEAT_SYS');
REPLACE INTO "tech_group_member" VALUES('elec_A',     'E_TRANS');
REPLACE INTO "tech_group_member" VALUES('elec_AB',    'NGCC');
REPLACE INTO "tech_group_member" VALUES('elec_AB',    'SOLPV');
REPLACE INTO "tech_group_member" VALUES('elec_AB',    'E_BATT');
REPLACE INTO "tech_group_member" VALUES('elec_AB',    'HEAT_SYS');
REPLACE INTO "tech_group_member" VALUES('elec_AB',    'E_TRANS');
REPLACE INTO "tech_group_member" VALUES('elec_C_ann', 'ANN_IMP');
REPLACE INTO "tech_group_member" VALUES('elec_C_ann', 'HEAT_ANN');
REPLACE INTO "efficiency" VALUES('A','ethos','IMP_NG',  2020,'NG', 1.0,NULL,NULL);
REPLACE INTO "efficiency" VALUES('A','NG',   'NGCC',    2015,'ELC',0.55,NULL,NULL);
REPLACE INTO "efficiency" VALUES('A','NG',   'NGCC',    2020,'ELC',0.55,NULL,NULL);
REPLACE INTO "efficiency" VALUES('A','NG',   'NGCC',    2025,'ELC',0.55,NULL,NULL);
REPLACE INTO "efficiency" VALUES('A','ethos','SOLPV',   2015,'ELC',1.0,NULL,NULL);
REPLACE INTO "efficiency" VALUES('A','ethos','SOLPV',   2020,'ELC',1.0,NULL,NULL);
REPLACE INTO "efficiency" VALUES('A','ethos','SOLPV',   2025,'ELC',1.0,NULL,NULL);
REPLACE INTO "efficiency" VALUES('A','ELC',  'E_BATT',  2020,'ELC',0.85,NULL,NULL);
REPLACE INTO "efficiency" VALUES('A','ELC',  'E_BATT',  2025,'ELC',0.85,NULL,NULL);
REPLACE INTO "efficiency" VALUES('A','ELC',  'HEAT_SYS',2020,'HEAT',1.0,NULL,NULL);
REPLACE INTO "efficiency" VALUES('A','ELC',  'HEAT_SYS',2025,'HEAT',1.0,NULL,NULL);
REPLACE INTO "efficiency" VALUES('B','ethos','IMP_NG',  2020,'NG', 1.0,NULL,NULL);
REPLACE INTO "efficiency" VALUES('B','NG',   'NGCC',    2015,'ELC',0.55,NULL,NULL);
REPLACE INTO "efficiency" VALUES('B','NG',   'NGCC',    2020,'ELC',0.55,NULL,NULL);
REPLACE INTO "efficiency" VALUES('B','NG',   'NGCC',    2025,'ELC',0.55,NULL,NULL);
REPLACE INTO "efficiency" VALUES('B','ELC',  'HEAT_SYS',2020,'HEAT',1.0,NULL,NULL);
REPLACE INTO "efficiency" VALUES('B','ELC',  'HEAT_SYS',2025,'HEAT',1.0,NULL,NULL);
REPLACE INTO "efficiency" VALUES('C','ethos','ANN_IMP',  2020,'ELC_C',1.0,NULL,NULL);
REPLACE INTO "efficiency" VALUES('C','ELC_C','HEAT_ANN', 2020,'HEAT_C',1.0,NULL,NULL);
REPLACE INTO "efficiency" VALUES('A-B','ELC','E_TRANS',2015,'ELC',0.95,NULL,NULL);
REPLACE INTO "efficiency" VALUES('B-A','ELC','E_TRANS',2015,'ELC',0.95,NULL,NULL);
REPLACE INTO "efficiency" VALUES('A-C','ELC','E_TRANS',2015,'ELC',0.95,NULL,NULL);
REPLACE INTO "efficiency" VALUES('C-A','ELC','E_TRANS',2015,'ELC',0.95,NULL,NULL);
REPLACE INTO "efficiency" VALUES('B-C','ELC','E_TRANS',2015,'ELC',0.95,NULL,NULL);
REPLACE INTO "efficiency" VALUES('C-B','ELC','E_TRANS',2015,'ELC',0.95,NULL,NULL);
REPLACE INTO "capacity_to_activity" VALUES('A','IMP_NG', 1.0,NULL,NULL);
REPLACE INTO "capacity_to_activity" VALUES('A','NGCC',   8.76,NULL,NULL);   -- GW → PJ/yr (8760 h)
REPLACE INTO "capacity_to_activity" VALUES('A','SOLPV',  8.76,NULL,NULL);
REPLACE INTO "capacity_to_activity" VALUES('A','E_BATT', 8.76,NULL,NULL);
REPLACE INTO "capacity_to_activity" VALUES('A','HEAT_SYS',1.0,NULL,NULL);
REPLACE INTO "capacity_to_activity" VALUES('B','IMP_NG', 1.0,NULL,NULL);
REPLACE INTO "capacity_to_activity" VALUES('B','NGCC',   8.76,NULL,NULL);
REPLACE INTO "capacity_to_activity" VALUES('B','HEAT_SYS',1.0,NULL,NULL);
REPLACE INTO "capacity_to_activity" VALUES('C','ANN_IMP',1.0,NULL,NULL);
REPLACE INTO "capacity_to_activity" VALUES('C','HEAT_ANN',1.0,NULL,NULL);
REPLACE INTO "capacity_to_activity" VALUES('A-B','E_TRANS',8.76,NULL,NULL);
REPLACE INTO "capacity_to_activity" VALUES('B-A','E_TRANS',8.76,NULL,NULL);
REPLACE INTO "capacity_to_activity" VALUES('A-C','E_TRANS',8.76,NULL,NULL);
REPLACE INTO "capacity_to_activity" VALUES('C-A','E_TRANS',8.76,NULL,NULL);
REPLACE INTO "capacity_to_activity" VALUES('B-C','E_TRANS',8.76,NULL,NULL);
REPLACE INTO "capacity_to_activity" VALUES('C-B','E_TRANS',8.76,NULL,NULL);
REPLACE INTO "storage_duration" VALUES('A','E_BATT',4.0,NULL);
REPLACE INTO "capacity_factor_tech" VALUES('A','summer','day',  'SOLPV',0.6,NULL);
REPLACE INTO "capacity_factor_tech" VALUES('A','summer','night','SOLPV',0.0,NULL);
REPLACE INTO "capacity_factor_tech" VALUES('A','winter','day',  'SOLPV',0.3,NULL);
REPLACE INTO "capacity_factor_tech" VALUES('A','winter','night','SOLPV',0.0,NULL);
REPLACE INTO "existing_capacity" VALUES('A','NGCC',  2015,0.5,'GW',NULL);
REPLACE INTO "existing_capacity" VALUES('A','SOLPV', 2015,0.2,'GW',NULL);
REPLACE INTO "existing_capacity" VALUES('B','NGCC',  2015,0.3,'GW',NULL);
REPLACE INTO "existing_capacity" VALUES('A-B','E_TRANS',2015,1.0,'GW',NULL);
REPLACE INTO "existing_capacity" VALUES('B-A','E_TRANS',2015,1.0,'GW',NULL);
REPLACE INTO "existing_capacity" VALUES('A-C','E_TRANS',2015,1.0,'GW',NULL);
REPLACE INTO "existing_capacity" VALUES('C-A','E_TRANS',2015,1.0,'GW',NULL);
REPLACE INTO "existing_capacity" VALUES('B-C','E_TRANS',2015,1.0,'GW',NULL);
REPLACE INTO "existing_capacity" VALUES('C-B','E_TRANS',2015,1.0,'GW',NULL);
REPLACE INTO "lifetime_tech" VALUES('A','IMP_NG',  100.0,NULL,NULL);
REPLACE INTO "lifetime_tech" VALUES('A','NGCC',    30.0, NULL,NULL);
REPLACE INTO "lifetime_tech" VALUES('A','SOLPV',   25.0, NULL,NULL);
REPLACE INTO "lifetime_tech" VALUES('A','E_BATT',  15.0, NULL,NULL);
REPLACE INTO "lifetime_tech" VALUES('A','HEAT_SYS',20.0, NULL,NULL);
REPLACE INTO "lifetime_tech" VALUES('B','IMP_NG',  100.0,NULL,NULL);
REPLACE INTO "lifetime_tech" VALUES('B','NGCC',    30.0, NULL,NULL);
REPLACE INTO "lifetime_tech" VALUES('B','HEAT_SYS',20.0, NULL,NULL);
REPLACE INTO "lifetime_tech" VALUES('C','ANN_IMP', 100.0,NULL,NULL);
REPLACE INTO "lifetime_tech" VALUES('C','HEAT_ANN',20.0, NULL,NULL);
REPLACE INTO "lifetime_tech" VALUES('A-B','E_TRANS',50.0,NULL,NULL);
REPLACE INTO "lifetime_tech" VALUES('B-A','E_TRANS',50.0,NULL,NULL);
REPLACE INTO "lifetime_tech" VALUES('C-A','E_TRANS',50.0,NULL,NULL);
REPLACE INTO "lifetime_tech" VALUES('A-C','E_TRANS',50.0,NULL,NULL);
REPLACE INTO "lifetime_tech" VALUES('B-C','E_TRANS',50.0,NULL,NULL);
REPLACE INTO "lifetime_tech" VALUES('C-B','E_TRANS',50.0,NULL,NULL);
REPLACE INTO "demand" VALUES('A',2020,'HEAT',5.0,NULL,NULL);
REPLACE INTO "demand" VALUES('A',2025,'HEAT',5.5,NULL,NULL);
REPLACE INTO "demand" VALUES('B',2020,'HEAT',3.0,NULL,NULL);
REPLACE INTO "demand" VALUES('B',2025,'HEAT',3.3,NULL,NULL);
REPLACE INTO "demand" VALUES('C',2020,'HEAT_C',1.0,NULL,NULL);
REPLACE INTO "demand" VALUES('C',2025,'HEAT_C',1.1,NULL,NULL);
REPLACE INTO "planning_reserve_credit" VALUES('A',    'NGCC',   1.0, NULL);
REPLACE INTO "planning_reserve_credit" VALUES('A',    'SOLPV',  0.15,NULL);
REPLACE INTO "planning_reserve_credit" VALUES('A',    'E_BATT', 0.9, NULL);
REPLACE INTO "planning_reserve_credit" VALUES('A',    'HEAT_SYS',0.0,NULL);
REPLACE INTO "planning_reserve_credit" VALUES('B',    'NGCC',   1.0, NULL);
REPLACE INTO "planning_reserve_credit" VALUES('B',    'HEAT_SYS',0.0,NULL);
REPLACE INTO "planning_reserve_credit" VALUES('A-B',  'E_TRANS',1.0, NULL);
REPLACE INTO "planning_reserve_credit" VALUES('B-A',  'E_TRANS',1.0, NULL);
REPLACE INTO "planning_reserve_credit" VALUES('C-B',  'E_TRANS',1.0, NULL);
REPLACE INTO "planning_reserve_credit" VALUES('B-C',  'E_TRANS',1.0, NULL);
REPLACE INTO "planning_reserve_credit" VALUES('C-A',  'E_TRANS',1.0, NULL);
REPLACE INTO "planning_reserve_credit" VALUES('A-C',  'E_TRANS',1.0, NULL);
REPLACE INTO "planning_reserve_credit" VALUES('C',    'ANN_IMP',1.0, NULL);
REPLACE INTO "planning_reserve_credit" VALUES('C',    'HEAT_ANN',0.0,NULL);
REPLACE INTO "planning_reserve_margin" VALUES('A',    'NGCC',      0.15,NULL);
REPLACE INTO "planning_reserve_margin" VALUES('A+B',  'elec_AB',   0.10,NULL);
REPLACE INTO "planning_reserve_margin" VALUES('C',    'elec_C_ann',0.20,NULL);
REPLACE INTO "operating_reserve_derate" VALUES('A','summer','NGCC',  0.95,NULL);
REPLACE INTO "operating_reserve_derate" VALUES('A','winter','NGCC',  0.90,NULL);
REPLACE INTO "operating_reserve_derate" VALUES('A','summer','SOLPV', 0.80,NULL);
REPLACE INTO "operating_reserve_derate" VALUES('A','winter','SOLPV', 0.50,NULL);
REPLACE INTO "operating_reserve_derate" VALUES('A','summer','E_BATT',0.90,NULL);
REPLACE INTO "operating_reserve_derate" VALUES('A','winter','E_BATT',0.90,NULL);
REPLACE INTO "operating_reserve_derate" VALUES('B','summer','NGCC',  0.95,NULL);
REPLACE INTO "operating_reserve_derate" VALUES('B','winter','NGCC',  0.90,NULL);
REPLACE INTO "operating_reserve_margin" VALUES('A',  'elec_A',    0.10,NULL);
REPLACE INTO "operating_reserve_margin" VALUES('B',  'NGCC',      0.10,NULL);
REPLACE INTO "operating_reserve_margin" VALUES('A+B','elec_AB',   0.08,NULL);
