-- One battery charged from free solar available only in d1 (issue #376).
-- Capacity 1, efficiency 0.8, C2A 1 and four slices of a quarter year each:
-- the battery may draw at most 0.25 in d1.
REPLACE INTO "metadata" VALUES('DB_MAJOR',4,'');
REPLACE INTO "metadata" VALUES('DB_MINOR',0,'');
REPLACE INTO "metadata_real" VALUES('default_loan_rate',0.05,'');
REPLACE INTO "metadata_real" VALUES('global_discount_rate',0.05,'');
REPLACE INTO "operator" VALUES('e','equal to');
REPLACE INTO "operator" VALUES('le','less than or equal to');
REPLACE INTO "operator" VALUES('ge','greater than or equal to');
REPLACE INTO "commodity_type" VALUES('p','physical commodity');
REPLACE INTO "commodity_type" VALUES('d','demand commodity');
REPLACE INTO "commodity_type" VALUES('s','source commodity');
REPLACE INTO "commodity_type" VALUES('e','emissions commodity');
REPLACE INTO "technology_type" VALUES('p','production technology');
REPLACE INTO "technology_type" VALUES('ps','storage production technology');
REPLACE INTO "sector_label" VALUES('electric',NULL);
REPLACE INTO "region" VALUES('R',NULL);
REPLACE INTO "time_period_type" VALUES('e','existing vintages');
REPLACE INTO "time_period_type" VALUES('f','future');
REPLACE INTO "time_period" VALUES(1,2020,'e');
REPLACE INTO "time_period" VALUES(2,2025,'f');
REPLACE INTO "time_period" VALUES(3,2030,'f');
REPLACE INTO "time_season" VALUES(1,'s1',1.0,NULL);
REPLACE INTO "time_of_day" VALUES(1,'d1',6.0,NULL);
REPLACE INTO "time_of_day" VALUES(2,'d2',6.0,NULL);
REPLACE INTO "time_of_day" VALUES(3,'d3',6.0,NULL);
REPLACE INTO "time_of_day" VALUES(4,'d4',6.0,NULL);
REPLACE INTO "commodity" VALUES('earth','s','source',NULL);
REPLACE INTO "commodity" VALUES('ELC','p','electricity',NULL);
REPLACE INTO "commodity" VALUES('RL','d','demand',NULL);
REPLACE INTO "technology" VALUES('sun','p','electric','solar','',0,0,0,0,0,0,0,0,'free, d1 only');
REPLACE INTO "technology" VALUES('gas','p','electric','gas','',0,0,0,0,0,0,0,0,'expensive');
REPLACE INTO "technology" VALUES('batt','ps','electric','battery','',0,0,0,0,0,0,0,0,'battery');
REPLACE INTO "technology" VALUES('load','p','electric','load','',0,0,0,0,0,0,0,0,'to demand');
REPLACE INTO "efficiency" VALUES('R','earth','sun',2025,'ELC',1.0,NULL,NULL);
REPLACE INTO "efficiency" VALUES('R','earth','gas',2025,'ELC',1.0,NULL,NULL);
REPLACE INTO "efficiency" VALUES('R','ELC','batt',2025,'ELC',0.8,NULL,NULL);
REPLACE INTO "efficiency" VALUES('R','ELC','load',2025,'RL',1.0,NULL,NULL);
REPLACE INTO "capacity_to_activity" VALUES('R','sun',1.0,NULL,'');
REPLACE INTO "capacity_to_activity" VALUES('R','gas',1.0,NULL,'');
REPLACE INTO "capacity_to_activity" VALUES('R','batt',1.0,NULL,'');
REPLACE INTO "capacity_to_activity" VALUES('R','load',1.0,NULL,'');
REPLACE INTO "capacity_factor_tech" VALUES('R','s1','d1','sun',1.0,NULL);
REPLACE INTO "capacity_factor_tech" VALUES('R','s1','d2','sun',0.0,NULL);
REPLACE INTO "capacity_factor_tech" VALUES('R','s1','d3','sun',0.0,NULL);
REPLACE INTO "capacity_factor_tech" VALUES('R','s1','d4','sun',0.0,NULL);
REPLACE INTO "storage_duration" VALUES('R','batt',24.0,NULL);
REPLACE INTO "cost_invest" VALUES('R','sun',2025,0.001,NULL,NULL);
REPLACE INTO "cost_invest" VALUES('R','gas',2025,0.001,NULL,NULL);
REPLACE INTO "cost_invest" VALUES('R','batt',2025,0.001,NULL,NULL);
REPLACE INTO "cost_invest" VALUES('R','load',2025,0.001,NULL,NULL);
REPLACE INTO "cost_variable" VALUES('R',2025,'gas',2025,100.0,'','');
REPLACE INTO "limit_capacity" VALUES('R',2025,'sun','le',10.0,'','');
REPLACE INTO "limit_capacity" VALUES('R',2025,'batt','ge',1.0,'','');
REPLACE INTO "limit_capacity" VALUES('R',2025,'batt','le',1.0,'','');
REPLACE INTO "demand" VALUES('R',2025,'RL',4.0,'','');
REPLACE INTO "demand_specific_distribution" VALUES('R',2025,'s1','d1','RL',0.25,NULL);
REPLACE INTO "demand_specific_distribution" VALUES('R',2025,'s1','d2','RL',0.25,NULL);
REPLACE INTO "demand_specific_distribution" VALUES('R',2025,'s1','d3','RL',0.25,NULL);
REPLACE INTO "demand_specific_distribution" VALUES('R',2025,'s1','d4','RL',0.25,NULL);
