name: temoa-py2
channels:
    - defaults
    - conda-forge
dependencies:
    - python=2
    - pyomo
    - xlwt
    - ipython
    - matplotlib
    - pandas
    - joblib
    - salib
    - pydoe
    - pyutilib
    - glpk