# NOTE:  This environment is UNTESTED.  It is just a couple version updates on the old conda environment
#        file.  Development has moved forward with pip and the requirements.txt
#        file without using conda.  Feedback/corrections/pull requests to tighten up this file for conda
#        users are welcome.

name: temoa-py3
channels:
    - defaults
    - conda-forge
dependencies:
    # Requirements for core model functionality
    - python=3.12
    - pyomo=6.7
    - pyomo.extras
    - xlwt
    - ipython
    - matplotlib
    - pandas
    - numpy
    - scipy
    - joblib
    - salib
    - pydoe
    - pyutilib
    - glpk
    - python-graphviz
    - ipykernel
    - jupyter
    - jupyter_contrib_nbextensions
    - seaborn
    - tabulate
    - xlsxwriter
    - plotly
    - pyam
    # cbc solver below cannot be installed via Conda on Windows
    - coincbc
    - pytest
    - deprecated
    - openpyxl
    - networkx
    - gravis

    # Below required to update documentation
    - sphinx
    - sphinx_rtd_theme
    - sphinxcontrib-htmlhelp
    - sphinxcontrib-serializinghtml
    - sphinxcontrib-bibtex
