"""
Type stubs for Pyomo external dependency.

This module provides type annotations for Pyomo classes and functions
that are heavily used in Temoa but don't have proper type information.
"""

from abc import ABC
from typing import Any, Optional, Protocol, Union, runtime_checkable

# Type aliases for common Pyomo patterns in Temoa
PyomoIndex = Union[str, int, float, tuple[Any, ...]]
PyomoExpression = Any  # Complex expressions are hard to type statically

# Protocol for Pyomo model components
@runtime_checkable
class PyomoComponent(Protocol):
    """Protocol for Pyomo model components."""

    name: str
    parent: Optional[Any]

    def pprint(self) -> None: ...
    def display(self) -> None: ...

# Forward declarations for Pyomo core types
class AbstractModel(ABC):
    """Base class for Pyomo models."""

    def __init__(self, name: Optional[str] = None, **kwargs: Any) -> None: ...

class Set:
    """Pyomo Set class for defining index sets."""

    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    @property
    def data(self) -> Any: ...
    @property
    def name(self) -> str: ...
    def __len__(self) -> int: ...
    def __iter__(self) -> Any: ...
    def __contains__(self, item: Any) -> bool: ...
    def __getitem__(self, key: Any) -> Any: ...
    def __or__(self, other: Any) -> 'Set': ...  # Union operation (|)
    def __mul__(self, other: Any) -> 'Set': ...  # Cross product operation (*)
    def __sub__(self, other: Any) -> 'Set': ...  # Difference operation (-)
    def first(self) -> Any: ...
    def last(self) -> Any: ...
    def next(self, value: Any) -> Any: ...
    def prev(self, value: Any) -> Any: ...
    def at(self, value: Any) -> Any: ...
    def add(self, value: Any) -> None: ...
    def construct(self) -> None: ...
    def difference(self, other: Any) -> 'Set': ...
    @classmethod
    def Skip(cls) -> 'Set': ...

class Param:
    """Pyomo Param class for defining parameters."""

    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    @property
    def value(self) -> Any: ...
    @property
    def name(self) -> str: ...
    def __getitem__(self, key: Any) -> Any: ...
    def __setitem__(self, key: Any, value: Any) -> None: ...
    def __contains__(self, key: Any) -> bool: ...
    def sparse_iterkeys(self) -> Any: ...  # iterator over non-default keys

class Var:
    """Pyomo Var class for defining decision variables."""

    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    @property
    def value(self) -> Any: ...
    def __getitem__(self, key: Any) -> Any: ...
    def __setitem__(self, key: Any, value: Any) -> None: ...
    def __contains__(self, key: Any) -> bool: ...
    def __mul__(self, other: Union[float, int, 'Expression']) -> 'Expression': ...
    def __rmul__(self, other: Union[float, int]) -> 'Expression': ...
    def keys(self) -> Any: ...
    def construct(self) -> None: ...

class Constraint:
    """Pyomo Constraint class for defining constraints."""

    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def __getitem__(self, key: Any) -> Any: ...
    def __setitem__(self, key: Any, value: Any) -> None: ...
    # Sentinel for skipping rule generation
    Skip: Any  # class attribute

class Objective:
    """Pyomo Objective class for defining optimization objectives."""

    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    @property
    def expr(self) -> Any: ...
    @property
    def active(self) -> bool: ...
    def getname(self, fully_qualified: bool = False) -> str: ...

class BuildAction:
    """Pyomo BuildAction class for model construction actions."""

    def __init__(self, rule: Any, **kwargs: Any) -> None: ...

class BuildCheck:
    """Pyomo BuildCheck class for model validation."""

    def __init__(self, rule: Any, **kwargs: Any) -> None: ...

class Expression:
    """Pyomo Expression class for mathematical expressions."""

    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def __contains__(self, key: Any) -> bool: ...
    def __mul__(self, other: Union[float, int, 'Var', 'Expression']) -> 'Expression': ...
    def __rmul__(self, other: Union[float, int]) -> 'Expression': ...
    def __truediv__(self, other: Union[float, int, 'Var', 'Expression']) -> 'Expression': ...
    def __le__(self, other: Union[float, int, 'Expression', 'Var']) -> Any: ...
    def __ge__(self, other: Union[float, int, 'Expression', 'Var']) -> Any: ...

# Common Pyomo function stubs
def value(obj: Any) -> Any: ...
def sum_product(*args: Any, **kwargs: Any) -> Any: ...
def quicksum(args: Any, **kwargs: Any) -> Expression: ...

# Export all stubs
__all__ = [
    'AbstractModel',
    'Set',
    'Param',
    'Var',
    'Constraint',
    'Objective',
    'BuildAction',
    'BuildCheck',
    'Expression',
    'PyomoIndex',
    'PyomoExpression',
    'PyomoComponent',
    'value',
    'sum_product',
    'quicksum',
]
