# temoa/data_io/component_manifest.py

from temoa.core.model import TemoaModel
from temoa.data_io.loader_manifest import LoadItem


def build_manifest(M: TemoaModel) -> list[LoadItem]:
    """
    Builds the manifest of all data components to be loaded into the Pyomo model.

    This declarative approach separates the configuration of what to load from the
    procedural logic of how to load it.

    Args:
        M: An instance of TemoaModel to link components.

    Returns:
        A list of LoadItem objects describing the data to be loaded.
    """
    manifest = [
        # === TIME SETS ===
        LoadItem(
            component=M.time_of_day,
            table='TimeOfDay',
            columns=['tod'],
            is_period_filtered=False,
            is_table_required=False,
            fallback_data=[('D',)],
        ),
        LoadItem(
            component=M.TimeSeason,
            table='TimeSeason',
            columns=['period', 'season'],
            custom_loader_name='_load_time_season',
            is_period_filtered=False,  # Custom loader handles myopic filtering
            is_table_required=False,
        ),
        LoadItem(
            component=M.SegFrac,
            table='TimeSegmentFraction',
            columns=['period', 'season', 'tod', 'segfrac'],
            custom_loader_name='_load_seg_frac',
            is_table_required=False,
        ),
        # === REGION SETS ===
        LoadItem(
            component=M.regions,
            table='Region',
            columns=['region'],
            is_period_filtered=False,
        ),
        # === TECH SETS ===
        LoadItem(
            component=M.tech_production,
            table='Technology',
            columns=['tech'],
            where_clause="flag LIKE 'p%'",
            validator_name='viable_techs',
            validation_map=(0,),
            is_period_filtered=False,
        ),
        LoadItem(
            component=M.tech_uncap,
            table='Technology',
            columns=['tech'],
            where_clause='unlim_cap > 0',
            validator_name='viable_techs',
            validation_map=(0,),
            is_period_filtered=False,
            is_table_required=False,  # unlim_cap is a newer column
        ),
        LoadItem(
            component=M.tech_baseload,
            table='Technology',
            columns=['tech'],
            where_clause="flag = 'pb'",
            validator_name='viable_techs',
            validation_map=(0,),
            is_period_filtered=False,
        ),
        LoadItem(
            component=M.tech_storage,
            table='Technology',
            columns=['tech'],
            where_clause="flag = 'ps'",
            validator_name='viable_techs',
            validation_map=(0,),
            is_period_filtered=False,
        ),
        LoadItem(
            component=M.tech_seasonal_storage,
            table='Technology',
            columns=['tech'],
            where_clause="flag = 'ps' AND seas_stor > 0",
            validator_name='viable_techs',
            validation_map=(0,),
            is_period_filtered=False,
        ),
        LoadItem(
            component=M.tech_reserve,
            table='Technology',
            columns=['tech'],
            where_clause='reserve > 0',
            validator_name='viable_techs',
            validation_map=(0,),
            is_period_filtered=False,
        ),
        LoadItem(
            component=M.tech_curtailment,
            table='Technology',
            columns=['tech'],
            where_clause='curtail > 0',
            validator_name='viable_techs',
            validation_map=(0,),
            is_period_filtered=False,
        ),
        LoadItem(
            component=M.tech_flex,
            table='Technology',
            columns=['tech'],
            where_clause='flex > 0',
            validator_name='viable_techs',
            validation_map=(0,),
            is_period_filtered=False,
        ),
        LoadItem(
            component=M.tech_exchange,
            table='Technology',
            columns=['tech'],
            where_clause='exchange > 0',
            validator_name='viable_techs',
            validation_map=(0,),
            is_period_filtered=False,
        ),
        LoadItem(
            component=M.tech_annual,
            table='Technology',
            columns=['tech'],
            where_clause='annual > 0',
            validator_name='viable_techs',
            validation_map=(0,),
            is_period_filtered=False,
        ),
        LoadItem(
            component=M.tech_retirement,
            table='Technology',
            columns=['tech'],
            where_clause='retire > 0',
            validator_name='viable_techs',
            validation_map=(0,),
            is_period_filtered=False,
        ),
        # Tech Groups
        LoadItem(
            component=M.tech_group_names,
            table='TechGroup',
            columns=['group_name'],
            is_period_filtered=False,
            is_table_required=False,
        ),
        # === COMMODITIES ===
        LoadItem(
            component=M.commodity_demand,
            table='Commodity',
            columns=['name'],
            where_clause="flag = 'd'",
            validator_name='viable_comms',
            validation_map=(0,),
            is_period_filtered=False,
        ),
        LoadItem(
            component=M.commodity_emissions,
            table='Commodity',
            columns=['name'],
            where_clause="flag = 'e'",
            is_period_filtered=False,
        ),
        LoadItem(
            component=M.commodity_physical,
            table='Commodity',
            columns=['name'],
            where_clause="flag LIKE '%p%' OR flag = 's' OR flag LIKE '%a%'",
            validator_name='viable_input_comms',
            validation_map=(0,),
            is_period_filtered=False,
        ),
        LoadItem(
            component=M.commodity_source,
            table='Commodity',
            columns=['name'],
            where_clause="flag = 's'",
            validator_name='viable_input_comms',
            validation_map=(0,),
            is_period_filtered=False,
        ),
        LoadItem(
            component=M.commodity_annual,
            table='Commodity',
            columns=['name'],
            where_clause="flag LIKE '%a%'",
            validator_name='viable_input_comms',
            validation_map=(0,),
            is_period_filtered=False,
        ),
        LoadItem(
            component=M.commodity_waste,
            table='Commodity',
            columns=['name'],
            where_clause="flag LIKE '%w%'",
            validator_name='viable_output_comms',
            validation_map=(0,),
            is_period_filtered=False,
        ),
        # === OPERATORS ===
        LoadItem(
            component=M.operator,
            table='Operator',
            columns=['operator'],
            is_period_filtered=False,
            is_table_required=False,
        ),
        # === PARAMS ===
        LoadItem(
            component=M.Demand, table='Demand', columns=['region', 'period', 'commodity', 'demand']
        ),
        LoadItem(
            component=M.CapacityToActivity,
            table='CapacityToActivity',
            columns=['region', 'tech', 'c2a'],
            validator_name='viable_rt',
            validation_map=(0, 1),
            is_period_filtered=False,
            is_table_required=False,
        ),
        LoadItem(
            component=M.CapacityFactorTech,
            table='CapacityFactorTech',
            columns=['region', 'period', 'season', 'tod', 'tech', 'factor'],
            validator_name='viable_rt',
            validation_map=(0, 4),
            is_table_required=False,
        ),
        LoadItem(
            component=M.CapacityFactorProcess,
            table='CapacityFactorProcess',
            columns=['region', 'period', 'season', 'tod', 'tech', 'vintage', 'factor'],
            validator_name='viable_rtv',
            validation_map=(0, 4, 5),
            is_table_required=False,
        ),
        LoadItem(
            component=M.LifetimeTech,
            table='LifetimeTech',
            columns=['region', 'tech', 'lifetime'],
            validator_name='viable_rt',
            validation_map=(0, 1),
            is_period_filtered=False,
            is_table_required=False,
        ),
        LoadItem(
            component=M.LifetimeProcess,
            table='LifetimeProcess',
            columns=['region', 'tech', 'vintage', 'lifetime'],
            validator_name='viable_rtv',
            validation_map=(0, 1, 2),
            is_period_filtered=False,
            is_table_required=False,
        ),
        LoadItem(
            component=M.EfficiencyVariable,
            table='EfficiencyVariable',
            columns=[
                'region',
                'period',
                'season',
                'tod',
                'input_comm',
                'tech',
                'vintage',
                'output_comm',
                'efficiency',
            ],
            validator_name='viable_ritvo',
            validation_map=(0, 4, 5, 6, 7),
            is_table_required=False,
        ),
        LoadItem(
            component=M.LifetimeSurvivalCurve,
            table='LifetimeSurvivalCurve',
            columns=['region', 'period', 'tech', 'vintage', 'fraction'],
            validator_name='viable_rtv',
            validation_map=(0, 2, 3),
            is_period_filtered=False,
            is_table_required=False,
        ),
        LoadItem(
            component=M.LoanLifetimeProcess,
            table='LoanLifetimeProcess',
            columns=['region', 'tech', 'vintage', 'lifetime'],
            validator_name='viable_rtv',
            validation_map=(0, 1, 2),
            is_period_filtered=False,
            is_table_required=False,
        ),
        LoadItem(
            component=M.CostFixed,
            table='CostFixed',
            columns=['region', 'period', 'tech', 'vintage', 'cost'],
            validator_name='viable_rtv',
            validation_map=(0, 2, 3),
        ),
        LoadItem(
            component=M.CostVariable,
            table='CostVariable',
            columns=['region', 'period', 'tech', 'vintage', 'cost'],
            validator_name='viable_rtv',
            validation_map=(0, 2, 3),
        ),
        LoadItem(
            component=M.CostEmission,
            table='CostEmission',
            columns=['region', 'period', 'emis_comm', 'cost'],
            is_table_required=False,
        ),
        LoadItem(
            component=M.LimitCapacity,
            table='LimitCapacity',
            columns=['region', 'period', 'tech_or_group', 'operator', 'capacity'],
            is_table_required=False,
        ),
        LoadItem(
            component=M.LimitNewCapacity,
            table='LimitNewCapacity',
            columns=['region', 'period', 'tech_or_group', 'operator', 'new_cap'],
            is_table_required=False,
        ),
        LoadItem(
            component=M.LimitCapacityShare,
            table='LimitCapacityShare',
            columns=['region', 'period', 'sub_group', 'super_group', 'operator', 'share'],
            is_table_required=False,
        ),
        LoadItem(
            component=M.LimitNewCapacityShare,
            table='LimitNewCapacityShare',
            columns=['region', 'period', 'sub_group', 'super_group', 'operator', 'share'],
            is_table_required=False,
        ),
        LoadItem(
            component=M.LimitActivityShare,
            table='LimitActivityShare',
            columns=['region', 'period', 'sub_group', 'super_group', 'operator', 'share'],
            is_table_required=False,
        ),
        LoadItem(
            component=M.LimitResource,
            table='LimitResource',
            columns=['region', 'tech_or_group', 'operator', 'cum_act'],
            is_period_filtered=False,
            is_table_required=False,
        ),
        LoadItem(
            component=M.LimitActivity,
            table='LimitActivity',
            columns=['region', 'period', 'tech_or_group', 'operator', 'activity'],
            is_table_required=False,
        ),
        LoadItem(
            component=M.LimitSeasonalCapacityFactor,
            table='LimitSeasonalCapacityFactor',
            columns=['region', 'period', 'season', 'tech', 'operator', 'factor'],
            validator_name='viable_rt',
            validation_map=(0, 3),
            is_table_required=False,
        ),
        LoadItem(
            component=M.LimitAnnualCapacityFactor,
            table='LimitAnnualCapacityFactor',
            columns=['region', 'period', 'tech', 'output_comm', 'operator', 'factor'],
            validator_name='viable_rpto',
            validation_map=(0, 1, 2, 3),
            is_table_required=False,
        ),
        LoadItem(
            component=M.LimitEmission,
            table='LimitEmission',
            columns=['region', 'period', 'emis_comm', 'operator', 'value'],
            is_table_required=False,
        ),
        LoadItem(
            component=M.EmissionActivity,
            table='EmissionActivity',
            columns=[
                'region',
                'emis_comm',
                'input_comm',
                'tech',
                'vintage',
                'output_comm',
                'activity',
            ],
            validator_name='viable_ritvo',
            validation_map=(0, 2, 3, 4, 5),
            is_period_filtered=False,
            is_table_required=False,
        ),
        LoadItem(
            component=M.EmissionEmbodied,
            table='EmissionEmbodied',
            columns=['region', 'emis_comm', 'tech', 'vintage', 'value'],
            validator_name='viable_rtv',
            validation_map=(0, 2, 3),
            is_period_filtered=False,
            is_table_required=False,
        ),
        LoadItem(
            component=M.EmissionEndOfLife,
            table='EmissionEndOfLife',
            columns=['region', 'emis_comm', 'tech', 'vintage', 'value'],
            validator_name='viable_rtv',
            validation_map=(0, 2, 3),
            is_period_filtered=False,
            is_table_required=False,
        ),
        LoadItem(
            component=M.ConstructionInput,
            table='ConstructionInput',
            columns=['region', 'input_comm', 'tech', 'vintage', 'value'],
            validator_name='viable_rtv',
            validation_map=(0, 2, 3),
            is_period_filtered=False,
            is_table_required=False,
        ),
        LoadItem(
            component=M.EndOfLifeOutput,
            table='EndOfLifeOutput',
            columns=['region', 'tech', 'vintage', 'output_comm', 'value'],
            validator_name='viable_rtv',
            validation_map=(0, 1, 2),
            is_period_filtered=False,
            is_table_required=False,
        ),
        LoadItem(
            # This is a composite loader. It will also populate M.tech_upramping
            component=M.RampUpHourly,
            table='RampUpHourly',
            columns=['region', 'tech', 'rate'],
            custom_loader_name='_load_ramping_up',
            validator_name='viable_rt',
            validation_map=(0, 1),
            is_period_filtered=False,
            is_table_required=False,
        ),
        LoadItem(
            # This is a placeholder for validation info, used by the custom loader above
            component=M.tech_upramping,
            table='RampUpHourly',
            columns=['tech'],
            validator_name='viable_techs',
            validation_map=(0,),
            is_period_filtered=False,
        ),
        LoadItem(
            # This is a composite loader. It will also populate M.tech_downramping
            component=M.RampDownHourly,
            table='RampDownHourly',
            columns=['region', 'tech', 'rate'],
            custom_loader_name='_load_ramping_down',
            validator_name='viable_rt',
            validation_map=(0, 1),
            is_period_filtered=False,
            is_table_required=False,
        ),
        LoadItem(
            # This is a placeholder for validation info, used by the custom loader above
            component=M.tech_downramping,
            table='RampDownHourly',
            columns=['tech'],
            validator_name='viable_techs',
            validation_map=(0,),
            is_period_filtered=False,
        ),
        LoadItem(
            component=M.RenewablePortfolioStandard,
            table='RPSRequirement',
            columns=['region', 'period', 'tech_group', 'requirement'],
            custom_loader_name='_load_rps_requirement',
            is_table_required=False,
        ),
        LoadItem(
            component=M.CapacityCredit,
            table='CapacityCredit',
            columns=['region', 'period', 'tech', 'vintage', 'credit'],
            validator_name='viable_rtv',
            validation_map=(0, 2, 3),
            is_table_required=False,
        ),
        LoadItem(
            component=M.ReserveCapacityDerate,
            table='ReserveCapacityDerate',
            columns=['region', 'period', 'season', 'tech', 'vintage', 'factor'],
            validator_name='viable_rtv',
            validation_map=(0, 3, 4),
            is_table_required=False,
        ),
        LoadItem(
            component=M.PlanningReserveMargin,
            table='PlanningReserveMargin',
            columns=['region', 'margin'],
            is_period_filtered=False,
            is_table_required=False,
        ),
        LoadItem(
            component=M.StorageDuration,
            table='StorageDuration',
            columns=['region', 'tech', 'duration'],
            validator_name='viable_rt',
            validation_map=(0, 1),
            is_period_filtered=False,
            is_table_required=False,
        ),
        LoadItem(
            component=M.LimitStorageFraction,
            table='LimitStorageLevelFraction',
            columns=[
                'region',
                'period',
                'season',
                'tod',
                'tech',
                'vintage',
                'operator',
                'fraction',
            ],
            validator_name='viable_rtv',
            validation_map=(0, 4, 5),
            is_table_required=False,
        ),
        # === Constraints with Special Logging ===
        LoadItem(
            component=M.LimitTechInputSplit,
            table='LimitTechInputSplit',
            columns=['region', 'period', 'input_comm', 'tech', 'operator', 'proportion'],
            validator_name='viable_rpit',
            validation_map=(0, 1, 2, 3),
            custom_loader_name='_load_limit_tech_input_split',
            is_table_required=False,
        ),
        LoadItem(
            component=M.LimitTechInputSplitAnnual,
            table='LimitTechInputSplitAnnual',
            columns=['region', 'period', 'input_comm', 'tech', 'operator', 'proportion'],
            validator_name='viable_rpit',
            validation_map=(0, 1, 2, 3),
            custom_loader_name='_load_limit_tech_input_split_annual',
            is_table_required=False,
        ),
        LoadItem(
            component=M.LimitTechOutputSplit,
            table='LimitTechOutputSplit',
            columns=['region', 'period', 'tech', 'output_comm', 'operator', 'proportion'],
            validator_name='viable_rpto',
            validation_map=(0, 1, 2, 3),
            custom_loader_name='_load_limit_tech_output_split',
            is_table_required=False,
        ),
        LoadItem(
            component=M.LimitTechOutputSplitAnnual,
            table='LimitTechOutputSplitAnnual',
            columns=['region', 'period', 'tech', 'output_comm', 'operator', 'proportion'],
            validator_name='viable_rpto',
            validation_map=(0, 1, 2, 3),
            custom_loader_name='_load_limit_tech_output_split_annual',
            is_table_required=False,
        ),
        LoadItem(
            component=M.LinkedTechs,
            table='LinkedTech',
            columns=['primary_region', 'primary_tech', 'emis_comm', 'driven_tech'],
            validator_name='viable_rtt',
            validation_map=(0, 1, 3),
            custom_loader_name='_load_linked_techs',
            is_period_filtered=False,
            is_table_required=False,
        ),
    ]
    return manifest
