"""
Type definitions and stubs for Temoa energy model.

This module provides comprehensive type annotations for the Temoa codebase,
including core model types, data structures, and interfaces.
"""

from typing import TYPE_CHECKING, Any

# Import all types from submodules
from .core_types import (
    Commodity,
    Commodityset,
    Configdict,
    ConstraintRule,
    DatabaseConnection,
    DatabaseCursor,
    IndexsetRule,
    InputCommodity,
    OutputCommodity,
    OutputConfig,
    Parameterdict,
    ParameterValue,
    Period,
    Periodset,
    Process,
    PyomoDomain,
    PyomoIndexset,
    QueryResult,
    Region,
    Regionset,
    ScenarioConfig,
    ScenarioName,
    Season,
    SolverConfig,
    SolverName,
    SparseIndex,
    Stringset,
    Technology,
    Techset,
    TimeOfDay,
    Vintage,
    Vintageset,
)
from .database_types import (
    CapacityFactorRow,
    ColumnName,
    CommodityQueryResult,
    CommodityRow,
    DatabaseSchema,
    DemandRow,
    EfficiencyQueryResult,
    EfficiencyRow,
    EmissionActivityRow,
    GenericQueryResult,
    SchemaVersion,
    TableName,
    TechnologyQueryResult,
    TechnologyRow,
    TimePeriodsRow,
)
from .dict_types import (
    ActiveRegionsForTechDict,
    ActiveRegionsForTechdict,
    BaseloadVintagesDict,
    BaseloadVintagesdict,
    CapacityConsumptionTechsDict,
    CapacityConsumptionTechsdict,
    CapacityFactorProcessDict,
    CapacityFactorProcessdict,
    CommodityBalanceDict,
    CommodityBalancedict,
    CommodityStreamProcessDict,
    CommodityStreamProcessdict,
    CurtailmentVintagesDict,
    CurtailmentVintagesdict,
    EfficiencyVariableDict,
    EfficiencyVariabledict,
    ExportRegionsDict,
    ExportRegionsdict,
    ImportRegionsDict,
    ImportRegionsdict,
    InputSplitAnnualVintagesDict,
    InputSplitAnnualVintagesdict,
    InputSplitVintagesDict,
    InputSplitVintagesdict,
    OutputSplitAnnualVintagesDict,
    OutputSplitAnnualVintagesdict,
    OutputSplitVintagesDict,
    OutputSplitVintagesdict,
    ProcessInputsByOutputDict,
    ProcessInputsByOutputdict,
    ProcessInputsDict,
    ProcessInputsdict,
    ProcessLoansDict,
    ProcessLoansdict,
    ProcessOutputsByInputDict,
    ProcessOutputsByInputdict,
    ProcessOutputsDict,
    ProcessOutputsdict,
    ProcessPeriodsDict,
    ProcessPeriodsdict,
    ProcessReservePeriodsDict,
    ProcessReservePeriodsdict,
    ProcessTechsDict,
    ProcessTechsdict,
    ProcessVintagesDict,
    ProcessVintagesdict,
    RampDownVintagesDict,
    RampDownVintagesdict,
    RampUpVintagesDict,
    RampUpVintagesdict,
    RetirementPeriodsDict,
    RetirementPeriodsdict,
    RetirementProductionProcessesDict,
    RetirementProductionProcessesdict,
    SeasonalStorageDict,
    SeasonalStoragedict,
    SequentialToSeasonDict,
    SequentialToSeasondict,
    StorageVintagesDict,
    StorageVintagesdict,
    SurvivalCurvePeriodsDict,
    SurvivalCurvePeriodsdict,
    SurvivalCurveProcessDict,
    SurvivalCurveProcessdict,
    TimeNextDict,
    TimeNextdict,
    TimeNextSequentialDict,
    TimeNextSequentialdict,
)
from .index_types import (
    PeriodSeasonSequential,
    PeriodSeasonTimeOfDay,
    RegionPeriod,
    RegionPeriodCommodity,
    RegionPeriodCommodityInputTechVintageOutput,
    RegionPeriodSeasonTimeInputTechVintageOutput,
    RegionPeriodSeasonTimeOfDay,
    RegionPeriodSeasonTimeOfDayCommodity,
    RegionPeriodSeasonTimeOfDayCommodityTechVintageOutput,
    RegionPeriodSeasonTimeOfDayTech,
    RegionPeriodSeasonTimeOfDayTechVintage,
    RegionPeriodTech,
    RegionPeriodTechVintage,
    RegionTech,
    RegionTechVintage,
)
from .set_types import (
    ActiveActivitySet,
    ActiveActivityset,
    ActiveCapacityAvailableSet,
    ActiveCapacityAvailableset,
    ActiveCapacityAvailableVintageSet,
    ActiveCapacityAvailableVintageset,
    ActiveCurtailmentSet,
    ActiveCurtailmentset,
    ActiveFlexAnnualSet,
    ActiveFlexAnnualset,
    ActiveFlexSet,
    ActiveFlexset,
    ActiveFlowAnnualSet,
    ActiveFlowAnnualset,
    ActiveFlowInStorageSet,
    ActiveFlowInStorageset,
    ActiveFlowSet,
    ActiveFlowset,
    GroupRegionActiveFlowSet,
    GroupRegionActiveFlowset,
    NewCapacitySet,
    NewCapacityset,
    SeasonalStorageLevelIndicesSet,
    SeasonalStorageLevelIndicesset,
    StorageLevelIndicesSet,
    StorageLevelIndicesset,
)
from .solver_types import (
    SolverOptions,
    SolverResults,
    SolverResultsProtocol,
    SolverStatus,
    SolverStatusEnum,
    TerminationCondition,
    TerminationConditionEnum,
)
from .validation_types import (
    ValidationError,
    ValidationResult,
    ValidationSeverity,
    ValidationWarning,
)

# DataFrame types for data processing
if TYPE_CHECKING:
    from .pandas_stubs import (
        DataFrame,
        PandasDtype,
        PandasIndex,
        Series,
    )

    TemoaDataFrame = DataFrame

    from numpy.typing import NDArray

    NumpyArray = NDArray[Any]

else:
    DataFrame = Any
    Series = Any
    PandasIndex = Any
    PandasDtype = Any
    TemoaDataFrame = Any  # pd.DataFrame at runtime

    NumpyArray = Any  # np.ndarray at runtime

# Export types for easy importing
__all__ = [
    # Core types
    'Region',
    'Period',
    'Technology',
    'Vintage',
    'Season',
    'TimeOfDay',
    'Commodity',
    'InputCommodity',
    'OutputCommodity',
    'Process',
    # Index types
    'RegionPeriod',
    'RegionPeriodTech',
    'RegionPeriodTechVintage',
    'RegionPeriodSeasonTimeInputTechVintageOutput',
    'SparseIndex',
    # Core index types
    'RegionTech',
    'RegionTechVintage',
    'RegionPeriodCommodity',
    'PeriodSeasonTimeOfDay',
    'RegionPeriodSeasonTimeOfDay',
    'RegionPeriodSeasonTimeOfDayTech',
    'RegionPeriodSeasonTimeOfDayTechVintage',
    'RegionPeriodSeasonTimeOfDayCommodity',
    'RegionPeriodCommodityInputTechVintageOutput',
    'RegionPeriodSeasonTimeOfDayCommodityTechVintageOutput',
    'PeriodSeasonSequential',
    # Process-related dictionary types (lowercase versions)
    'ProcessInputsdict',
    'ProcessOutputsdict',
    'ProcessLoansdict',
    'ProcessInputsByOutputdict',
    'ProcessOutputsByInputdict',
    'ProcessTechsdict',
    'ProcessReservePeriodsdict',
    'ProcessPeriodsdict',
    'RetirementPeriodsdict',
    'ProcessVintagesdict',
    'SurvivalCurvePeriodsdict',
    'CapacityConsumptionTechsdict',
    'RetirementProductionProcessesdict',
    # Process-related dictionary types (capitalized versions)
    'ProcessInputsDict',
    'ProcessOutputsDict',
    'ProcessLoansDict',
    'ProcessInputsByOutputDict',
    'ProcessOutputsByInputDict',
    'ProcessTechsDict',
    'ProcessReservePeriodsDict',
    'ProcessPeriodsDict',
    'RetirementPeriodsDict',
    'ProcessVintagesDict',
    'SurvivalCurvePeriodsDict',
    'CapacityConsumptionTechsDict',
    'RetirementProductionProcessesDict',
    # Commodity flow dictionary types (lowercase versions)
    'CommodityStreamProcessdict',
    'CommodityBalancedict',
    # Commodity flow dictionary types (capitalized versions)
    'CommodityStreamProcessDict',
    'CommodityBalanceDict',
    # Technology classification dictionary types (lowercase versions)
    'BaseloadVintagesdict',
    'CurtailmentVintagesdict',
    'StorageVintagesdict',
    'RampUpVintagesdict',
    'RampDownVintagesdict',
    'InputSplitVintagesdict',
    'InputSplitAnnualVintagesdict',
    'OutputSplitVintagesdict',
    'OutputSplitAnnualVintagesdict',
    # Technology classification dictionary types (capitalized versions)
    'BaseloadVintagesDict',
    'CurtailmentVintagesDict',
    'StorageVintagesDict',
    'RampUpVintagesDict',
    'RampDownVintagesDict',
    'InputSplitVintagesDict',
    'InputSplitAnnualVintagesDict',
    'OutputSplitVintagesDict',
    'OutputSplitAnnualVintagesDict',
    # Time sequencing dictionary types (lowercase versions)
    'TimeNextdict',
    'TimeNextSequentialdict',
    'SequentialToSeasondict',
    # Time sequencing dictionary types (capitalized versions)
    'TimeNextDict',
    'TimeNextSequentialDict',
    'SequentialToSeasonDict',
    # Geography/exchange dictionary types (lowercase versions)
    'ExportRegionsdict',
    'ImportRegionsdict',
    'ActiveRegionsForTechdict',
    # Geography/exchange dictionary types (capitalized versions)
    'ExportRegionsDict',
    'ImportRegionsDict',
    'ActiveRegionsForTechDict',
    # Switching/boolean flag dictionary types (lowercase versions)
    'EfficiencyVariabledict',
    'CapacityFactorProcessdict',
    'SeasonalStoragedict',
    'SurvivalCurveProcessdict',
    # Switching/boolean flag dictionary types (capitalized versions)
    'EfficiencyVariableDict',
    'CapacityFactorProcessDict',
    'SeasonalStorageDict',
    'SurvivalCurveProcessDict',
    # set types for sparse indexing (lowercase versions)
    'ActiveFlowset',
    'ActiveFlowAnnualset',
    'ActiveFlexset',
    'ActiveFlexAnnualset',
    'ActiveFlowInStorageset',
    'ActiveCurtailmentset',
    'ActiveActivityset',
    'StorageLevelIndicesset',
    'SeasonalStorageLevelIndicesset',
    'NewCapacityset',
    'ActiveCapacityAvailableset',
    'ActiveCapacityAvailableVintageset',
    'GroupRegionActiveFlowset',
    # set types for sparse indexing (capitalized versions)
    'ActiveFlowSet',
    'ActiveFlowAnnualSet',
    'ActiveFlexSet',
    'ActiveFlexAnnualSet',
    'ActiveFlowInStorageSet',
    'ActiveCurtailmentSet',
    'ActiveActivitySet',
    'StorageLevelIndicesSet',
    'SeasonalStorageLevelIndicesSet',
    'NewCapacitySet',
    'ActiveCapacityAvailableSet',
    'ActiveCapacityAvailableVintageSet',
    'GroupRegionActiveFlowSet',
    # Pyomo domain types
    'PyomoDomain',
    'PyomoIndexset',
    # Data structure types
    'ParameterValue',
    'Parameterdict',
    'Stringset',
    'Techset',
    'Commodityset',
    'Regionset',
    'Periodset',
    'Vintageset',
    # Database types
    'DatabaseConnection',
    'DatabaseCursor',
    'QueryResult',
    # Data processing types
    'TemoaDataFrame',
    'NumpyArray',
    # Configuration types
    'ScenarioName',
    'Configdict',
    'ScenarioConfig',
    'SolverConfig',
    'OutputConfig',
    'SolverName',
    # Constraint and rule types
    'ConstraintRule',
    'IndexsetRule',
    # Pyomo stub types (for type checking)
    'PyomoSet',
    'PyomoParam',
    'PyomoVar',
    'PyomoConstraint',
    'PyomoBuildAction',
    'PyomoObjective',
    'AbstractModel',
    # Pandas stub types (for type checking)
    'DataFrame',
    'Series',
    'PandasIndex',
    'PandasDtype',
    # Solver types
    'SolverResults',
    'SolverStatus',
    'TerminationCondition',
    'SolverStatusEnum',
    'TerminationConditionEnum',
    'SolverResultsProtocol',
    'SolverOptions',
    # Database types
    'TableName',
    'ColumnName',
    'SchemaVersion',
    'DatabaseSchema',
    'TechnologyRow',
    'CommodityRow',
    'TimePeriodsRow',
    'EfficiencyRow',
    'CapacityFactorRow',
    'DemandRow',
    'EmissionActivityRow',
    'TechnologyQueryResult',
    'CommodityQueryResult',
    'EfficiencyQueryResult',
    'GenericQueryResult',
    # Validation types
    'ValidationSeverity',
    'ValidationError',
    'ValidationWarning',
    'ValidationResult',
]
